name: apps_by_rhino
description: Website to showcase all my websites and apps!

publish_to: 'Web'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  google_fonts: ^3.0.1
  wave: ^0.2.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/apps/